### ISSUE TITLE
Unable to instrument Java Service with QUARKUS Framework in Newrelic

### ISSUE THREAD

**Issue by Sarang-Dharme-od** [newrelic-experimental/newrelic-java-quarkus#5]
We have been trying to instrument Java kube Service with QUARKUS Framework in Newrelic following the steps suggested in this project. I have created extension directory and downloaded Jars extracting from https://github.com/newrelic-experimental/newrelic-java-quarkus/releases/download/2.0/instrumentation.tar and restated the application. However, the application is not getting instrumented. As soon as I referance newrelic.jar at ENTRYPOINT, JVM shutdown and agent stops. The error log screenshot has been attached with this ticket. Kindly provide your suggestions and help to instrument QUARKUS service. Thanks in advance!

![image](https://github.com/newrelic-experimental/newrelic-java-quarkus/assets/53090010/8fcc127d-4e9f-4481-bf2e-b3304c68c7a2)

1)Is it enough to download Jars in extension directory or need to reference application Jar & downloaded jar at Dockerfile ENTRYPOINT?
2)Is there any specific location to copy newrelic.jar and configuration file?
3)Is there any specific string in log signifies successful instrumentation?

**Comment by gsidhwani-nr** [comment]
I have updated the ReadMe with clear instructions. Please let me know if you are still facing any issues.
