### ISSUE TITLE
Excessive log spam on stdout when resteasy instrumentation is active

### ISSUE THREAD

**Issue by kherock** [newrelic-experimental/newrelic-java-quarkus#9]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

I'm attempting to set up more detailed logging on a Quarkus application, but since installing `newrelic-java-quarkus`, my server logs have ballooned in size due to the extension logging directly to stdout.

## Steps to Reproduce

[NOTE]: # ( Please be as specific as possible. )

Run a Quarkus server instrumented with the New Relic Java agent and the `quarkus-resteasy-2.14.1.jar` installed in the `/opt/newrelic/extensions` directory. In my setup, I am running Keycloak 22.

Upon processing a HTTP request, the server should log `(GET) /:/` or similar depending on the computed transaction name.

## Expected Behavior

[NOTE]: # ( Tell us what you expected to happen. )

New Relic instrumentation should not add any logs to the server console after startup.

## Relevant Logs / Console output

[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )

## Additional context

`System.out.println` is here
https://github.com/newrelic-experimental/newrelic-java-quarkus/blob/main/quarkus-resteasy-2.11/src/main/java/com/newrelic/instrumentation/quarkus/resteasy/Utils.java

it is commented out in the `quarkus-resteasy-reactive-*` extensions, so it seems like this was left in by mistake.

**Comment by dhilpipre** [comment]
Thanks for pointing this out.  Yes it was left in by mistake.  We are in the process of correcting it and should have an updated release in the next day or so.

**Comment by dhilpipre** [comment]
System.out.print lines removed and we have generated a new release

https://github.com/newrelic-experimental/newrelic-java-quarkus/releases/tag/v2.1.2
